### ISSUE TITLE
Feature: Integrate with `$ sudo -l` output

### ISSUE THREAD

**Issue by alichtman** [Anon-Exploiter/SUID3NUM#6]

**Comment by Anon-Exploiter** [comment]
Hi, 

I've thought of doing this in the past but that will require some work, if there is any binary you can invoke with sudo, exploitation of that comes in handy since you can list that. 

With SUID3NUM, you've to find the not-so-common bins and then exploit it, that was the reason I wrote this. There are many other scripts (including linpeas, LSE, linenum, etc.) which execute `sudo -l` and show you the bins you can exploit, utilize GTFObins and w00t.
